### ISSUE TITLE
doesn't build with node v0.11.14

### ISSUE THREAD

**Issue by silverbucket** [xmppo/node-expat#100]
There's tons of output for each file it fails to compile, but here's an example of the failures I get when trying to install node-xmpp as a dependency of sockethub using node `v0.11.14` .

```
In file included from ../node-expat.cc:1:0:
../node-expat.cc: In member function ‘void Parser::Emit(int, v8::Handle<v8::Value>*)’:
../node_modules/nan/nan.h:159:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node-expat.cc:423:40: note: in expansion of macro ‘NanSymbol’
     Local<Function> emit = handle->Get(NanSymbol("emit")).As<Function>();
                                        ^
../node-expat.cc:423:70: error: expected primary-expression before ‘>’ token
     Local<Function> emit = handle->Get(NanSymbol("emit")).As<Function>();
                                                                      ^
../node-expat.cc:423:72: error: expected primary-expression before ‘)’ token
     Local<Function> emit = handle->Get(NanSymbol("emit")).As<Function>();
                                                                        ^
In file included from ../node-expat.cc:1:0:
../node_modules/nan/nan.h: In instantiation of ‘void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
../node_modules/nan/nan.h:717:34:   required from here
../node_modules/nan/nan.h:373:5: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
     ^
node_expat.target.mk:92: recipe for target 'Release/obj.target/node_expat/node-expat.o' failed
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory '/home/nkj/code/sockethub/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/ltx/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.16.4-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nkj/code/sockethub/node_modules/simple-xmpp/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/ltx/node_modules/node-expat
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```
